project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.flatpages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

urlpatterns += [
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('terms-of-use/', views.flatpage, {'url': '/terms-of-use/'}, name='terms-of-use'),
    path('policy/', views.flatpage, {'url': '/policy/'}, name='policy'),
    path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
"""
App urls
"""

from django.contrib.auth.views import PasswordResetView
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='home',),
    path('accounts/profile/', views.profile, name = 'profile'),
    path('accounts/signup/', views.signup.as_view(), name='signup'),
    path('accounts/signup/company/', views.signup_company, name='signup_company'),
    path('accounts/signup/client/', views.signup_client, name='signup_client'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('lots/', views.CompanyLotsListView.as_view(), name='lots'),
    path('lot/<slug:slug>', views.CompanyLotDetailView.as_view(), name='lot_detail'),
    
]

website/models.py
from django.contrib.auth.models import User
from django.core.validators import (MaxValueValidator, MinValueValidator,
                                    RegexValidator)
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_resized import ResizedImageField

from website.utils import slugify


# Abstract user
class SiteUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = ResizedImageField("Зображення профілю", size=[150, 150], upload_to="profiles/%Y/%m/%d", null=True, blank=True)

    phone_regex = RegexValidator(regex=r'((\+38)?\(?\d{3}\)?[\s\.-]?(\d{7}|\d{3}[\s\.-]\d{2}[\s\.-]\d{2}|\d{3}-\d{4}))', message="Номер телефону повинен бути введений у форматі: '+380XXXXXXXXX")
    phone = models.CharField("Телефон", validators=[phone_regex], max_length=17, blank=False)

    class Meta:
        abstract = True


# Created users
class Client(SiteUser):
    name = models.CharField("ПІБ", max_length=100)
    # lot = models.ForeignKey(ClientLot, verbose_name="Лот", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Клієнт"
        verbose_name_plural = "Клієнти"
    

class Company(SiteUser):
    name = models.CharField("Назва компанії", max_length=100)
    edrpou = models.PositiveIntegerField("ЄДРПОУ", blank=True, null=True)
    location = models.CharField("Місцезнаходження", max_length=100, blank=True)
    website_link = models.URLField("Вебсайт", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Компанія"
        verbose_name_plural = "Компанії"


# Lot category
class Category(models.Model):
    image = ResizedImageField("Картинка", size = [150, 150], crop=['middle', 'center'], upload_to="categories/%Y/%m/%d", null=True, blank=True)
    name = models.CharField("Назва категорії", max_length=150)
    description = models.TextField("Опис")
    url = models.SlugField("Посилання", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"

    def get_absolute_url(self):
        return f"{reverse('lots')}?category={self.url}"


# Lot
class Lot(models.Model):
    name = models.CharField("Назва лоту", max_length=255)
    description = models.TextField("Опис")
    
    category = models.ForeignKey(
        Category, verbose_name="Категорія", on_delete=models.SET_NULL, null=True
    )
    
    price = models.PositiveIntegerField("Стартова ціна")
    current_price = models.PositiveIntegerField("Ціна зараз", default = None, blank=True, null=True)
    price_gap = models.PositiveIntegerField("Зміна ціни", help_text = "(Ціна, на яку можуть змінювати ціну ставки)", blank=True, default=30)
    date_created = models.DateTimeField("Створено", auto_now_add=True, editable=False)
    date_end = models.DateTimeField("Завершується")
    url = models.SlugField("Посилання", unique=True, blank=True, null=True)
    is_active = models.BooleanField('Активний', default=True)

    class Meta:
        abstract = True

    def get_absolute_url(self):
        return reverse("lot_detail", kwargs={"slug": self.url})
    
    


class ClientLot(Lot):
    owner = models.ForeignKey(Client, verbose_name="Власник лоту", on_delete=models.CASCADE)
    lot_type = models.CharField(max_length=50, editable=False, default="reverse_auction")

    def __str__(self):
        return str(self.owner)

    class Meta:
        verbose_name = "Лот клієнта"
        verbose_name_plural = "Лоти клієнта"

    def save(self, *args, **kwargs):
        # Do if this is a new instance
        if not self.pk:
            self.current_price = self.price

            slug = slugify(self.name)[:50]
            if not ClientLot.objects.filter(url = slug).exists():
                self.url = slug
            else:
                super(ClientLot, self).save(*args, **kwargs)
                id_length = len(str(self.id)) + 1
                slugify(self.name)[:50 - id_length]
                self.url = slug  + '-' + str(self.id)
            
        super(ClientLot, self).save(*args, **kwargs)

class CompanyLot(Lot):
    owner = models.ForeignKey(Company, verbose_name="Власник лоту", on_delete=models.CASCADE)
    lot_type = models.CharField(max_length=50, editable=False, default="auction")

    def __str__(self):
        return f'{self.name} - ({self.owner})'

    class Meta:
        verbose_name = "Лот компанії"
        verbose_name_plural = "Лоти компаній"

    def first_image(self):
        return self.images.first()

    def save(self, *args, **kwargs):
        # Do if this is a new instance
        if not self.pk:
            
            self.current_price = self.price
        
            slug = slugify(self.name)[:50]
            # Create slug if it does not exists yet
            if not CompanyLot.objects.filter(url = slug).exists():
                self.url = slug
            # If slug exists add lot id to the end of the slug
            else:
                super(CompanyLot, self).save(*args, **kwargs)
                id_length = len(str(self.id)) + 1
                slug = slugify(self.name)[:50 - id_length]
                self.url = slug  + '-' + str(self.id)
        
        super(CompanyLot, self).save(*args, **kwargs)

class LotPhoto(models.Model):
    photo = ResizedImageField('Фото', crop=['middle', 'center'], upload_to="lot_photos/%Y/%m/%d", null=True)
    lot = models.ForeignKey(
        CompanyLot, on_delete=models.CASCADE,
        related_name='images'
    )

    class Meta:
        verbose_name = "Фотографія лота"
        verbose_name_plural = "Фотографії лотів"

    def __str__(self):
        return f'{self.lot.name} - ({self.lot.owner})'


class BidClientLot(models.Model):
    lot = models.ForeignKey(
        ClientLot, on_delete = models.CASCADE
    )
    hiden_name = models.CharField("Ім'я", max_length=255)
    price = models.PositiveIntegerField("Ставка")
    date_created = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        verbose_name = "Ставка на лот клієнта"
        verbose_name_plural = "Ставки на лот клієнта"

class BidCompanyLot(models.Model):
    lot = models.ForeignKey(
        CompanyLot, on_delete = models.CASCADE
    )
    bidder = models.ForeignKey(Client, verbose_name='bid', on_delete = models.CASCADE, default=None)
    hiden_name = models.CharField("Ім'я", max_length=255)
    price = models.PositiveIntegerField("Ставка")
    date_created = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        verbose_name = "Ставка на лот компанії"
        verbose_name_plural = "Ставки на лот компанії"

    def __str__(self):
        return self.hiden_name


# Reviews
class CompanyReview(models.Model):
    lot = models.ForeignKey(CompanyLot, on_delete=models.CASCADE)
    comment_owner = models.ForeignKey(Client, on_delete=models.CASCADE)
    description = models.TextField("Опис")
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    rating = models.SmallIntegerField(default=0, 
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
    ]
    )

    def __str__(self):
        return str(self.comment_owner)

    class Meta:
        verbose_name = "Відгук клієнта"
        verbose_name_plural = "Відгуки клієнтів"
    


class ClientReview(models.Model):
    lot = models.ForeignKey(ClientLot, on_delete=models.CASCADE)
    comment_owner = models.ForeignKey(Company, on_delete=models.CASCADE)
    description = models.TextField("Опис")
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    rating = models.SmallIntegerField(default=0, 
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
    ]
    )

    def __str__(self):
        return str(self.comment_owner)

    class Meta:
        verbose_name = "Відгук компанії"
        verbose_name_plural = "Відгуки компаній"

website/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User

from website.models import ClientLot, CompanyLot, BidCompanyLot, LotPhoto

from .models import Client, Company


# Registration
class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email', error_messages={'exists': 'Електронна адеса вже використовується'})

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        # user.groups.add(Group.objects.get_or_create(name="client"))
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_messages['exists'])
        return self.cleaned_data['email']


class ClientSignForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'profile_pic', 'phone')


class CompanySignForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'profile_pic', 'phone', 'edrpou', 'location', 'website_link',)


class CreateBid(forms.ModelForm):
    class Meta:
        model = BidCompanyLot
        fields = ('price',)

    def clean_price(self):
        price = self.cleaned_data.get('price')
        return price

    def save(self, commit=True):
        bid = super(CreateBid, self).save(commit=False)
        bid.price = self.cleaned_data['price']
        if commit:
            bid.save()
        return bid
    

# Lot add
class ClientLotCreate(forms.ModelForm):
    class Meta:
        model = ClientLot
        fields = ('name', 'description','category','price','price_gap')

    
class CompanyLotCreate(forms.ModelForm):
    class Meta:
        model = CompanyLot
        fields = ('name', 'description','category','price','price_gap',)


class LotPhotoCreate(forms.ModelForm):
    class Meta:
        model = LotPhoto
        fields = ('photo',)

website/templates/website/index.html
{% extends 'website/main.html' %}
{% load static %}

{% block title %}Лоти{% endblock title %}

{% block content %}

<div class="container">
    <div class="my-5">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <a href="{% url 'lots' %}?phones">
                <img class="d-block w-100" src="{% static 'images/carousel/phones.jpg' %}" alt="First slide">
                </a>
            </div>
            <div class="carousel-item">
            <a href="{% url 'lots' %}?notebooks">
                <img class="d-block w-100" src="{% static 'images/carousel/laptop.jpg' %}" alt="Second slide">
                </a>
            </div>
            <div class="carousel-item">
            <a href="{% url 'lots' %}?tablets">
                <img class="d-block w-100" src="{% static 'images/carousel/tablets.jpg' %}" alt="Third slide">
                </a>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    </div>

    <h2>Оберіть категорію:</h2>
    <hr>
    <div class="row" style="justify-content: space-between;">
        {% for category in categories %}
        <div class="category-block mx-3">
            <a href="{% url 'lots' %}?{{ category.url }}">
                <img src="{{ category.image.url }}" alt="Картинка категорії">
            </a>
            <p>{{ category.name }}</p>
        </div>
        {% endfor %}
    </div>

    <h2 class="sear-head editContent">Останні лоти</h2>
    <hr>
    {% for lot in company_lots %}
        <div class="special-sec1 row mt-3 editContent">
            <div class="img-deals card col-md-8 offset-md-1" style="border:none;">
                <img src="{{lot.first_image.photo.url}}" class="img-fluid" alt="">
                <div class="row">
                    <h4 class="editContent col-md">{{ lot.name }}</h4>
                    <div class="col-md my-auto">
                        <table>
                            <tr style="font-size:20px;">
                                <td>Від:&nbsp;</td>
                                <td><span class="font-size-16 text-danger">{{ lot.price }}&nbsp;грн.</span></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <a href="{{ lot.get_absolute_url }}" class="editContent stretched-link"></a>
            </div>
        </div>
    {% endfor %}
</div>

    
{% endblock content %}

website/templates/website/lot_detail.html
{% extends 'website/main.html' %}
{% load static %}
{% block title %}Лот "{{ lot.name }}"{% endblock title %}

{% block extra_head %}
<link href="{% static 'styles/lot_detail.css' %}" rel="stylesheet">
{% endblock extra_head %}

{% block extra_script %}
<script>
    {% if messages %} {%for message in messages %}
    window.setTimeout(function () {
        alert('{{message}}');
    }, 500); {% endfor %} {% endif %}

// Set the date we're counting down to
var countDownDate = new Date("{{ lot.date_end|date:"c" }}").getTime();
  
// Update the count down every 1 second
var x = setInterval(function() {

//Get server timezone
var serverTimeZoneOffset = "{% now "Z" %}";

// Get today's date and time
var now = new Date(new Date().getTime());

// Create offseted time
var offsetTime = new Date(now + serverTimeZoneOffset).getTime();

// Find the distance between now and the count down date
var distance = countDownDate - offsetTime;

console.log("Time now ", offsetTime);
console.log("Time end ", countDownDate);
console.log("Distance ", distance);
    
// Time calculations for days, hours, minutes and seconds
var days = Math.floor(distance / (1000 * 60 * 60 * 24));
var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
// Output the result in an element with id="countdown"
document.getElementById("countdown").innerHTML = days + " дн. " + hours + " г. "
+ minutes + " хв. " + seconds + " с.";
    
// If the count down is over, write some text 
if (distance < 0) {
  clearInterval(x);
  {% if lot.is_active %}location.reload();{% endif %}
  document.getElementById("countdown").innerHTML = "Лот завершився";
}
}, 1000);
</script>
{% endblock extra_script %}

{% block content %}
<main id="main-site">

    <!--   product  -->
    <section id="product" class="py-3">
        <div class="container">
            <div class="row">
                <div class="col-md">
                {% if lot.first_image.photo.url %}
                    <img src="{{ lot.first_image.photo.url }}" alt="Картинка лоту" class="img-fluid">
                {% else %}
                <div style="background-image: url(..{% static 'images/images.png' %}); background-size: cover; height:100%;"></div>
                {% endif %}
                </div>
                <div class="col-md-6 py-5">
                    <h5 class="font-size-20">{{ lot.name }}</h5>
                    <small>Власник {{ lot.owner }}</small>
                    {% comment %} <div class="d-flex">
                        <div class="rating text-warning font-size-12">
                            <span><i class="fas fa-star"></i></span>
                            <span><i class="fas fa-star"></i></span>
                            <span><i class="fas fa-star"></i></span>
                            <span><i class="fas fa-star"></i></span>
                            <span><i class="far fa-star"></i></span>
                        </div>
                        <a href="#" class="px-2 font-size-14">20,534 ratings | 1000+ answered questions</a>
                    </div> {% endcomment %}
                    <hr class="m-0">

                    <!---    product price       -->
                    <table class="my-3">
                        <tr class="font-size-20">
                            <td>Ціна:&nbsp;</td>
                            <td class="font-size-20 text-danger"><span>{{ lot.current_price }}</span>&nbsp;грн.<small
                                    class="text-dark font-size-12">&nbsp;&nbsp;Найбільша ставка наразі</small></td>
                        </tr>
                    </table>
                    <table class="my-3">
                        <tr class="font-size-14">
                            <td>Стартова ціна:&nbsp;</td>
                            <td><span class="font-size-16 text-danger">{{ lot.price }}&nbsp;грн.</span></td>
                        </tr>
                    </table>

{% if lot.is_active %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {% include 'includes/bid_form.html' with form=form %}
                        <div class="form-row font-size-16">
                            {% comment %} <div class="col">
                                <button type="submit" class="btn btn-danger form-control">Купити одразу</button>
                            </div> {% endcomment %}
                            <div class="col-md-5">
                                <button type="submit" class="btn btn-warning form-control">Зробити ставку</button>
                            </div>
                        </div>
                    </form>
{% else %}
<p class="font-size-20"><i class="bi bi-emoji-laughing"></i>&nbsp;&nbsp;Переміг: {{ bids.0 }}</p>
{% endif %}
                    <!---    !product price       -->

                    <!-- additional info -->
                    <div class="additional-info mt-4 ml-2">
                        <p><i class="bi bi-cash-stack"></i><i class="bi bi-arrow-up"></i>Мінімальний розмір ставки: {{ lot.price_gap }} грн.</p>

                        <p><i class="bi bi-people"></i>&nbsp;&nbsp;Зроблено ставок: {{ lot.bidcompanylot_set.count }}, Лідер: {{ bids.0 }}</p>

                        <p><i class="bi bi-clock"></i>&nbsp;&nbsp;<strong id="countdown"></strong>, ({{ lot.date_end }})</p>
                    </div>

                    <!-- !additional info -->
                </div>

                <div class="col-12 mt-4">
                    <h4 class="font-size-20">Опис лоту</h4>
                    <hr>
                    <p class="font-size-14">{{ lot.description }}</p>

                    <h4 class="font-size-20">Ставки</h4>
                    <hr>

                    <div class="bid-table">

                        <table width="100%">
                            <tbody>
                                <tr align="left">
                                    <th>Користувач</th>
                                    <th>Ціна</th>
                                    <th>Дата</th>
                                </tr>

                                {% for bid in bids %}
                                <tr height="40px">
                                    <td width="30%">{{ bid.hiden_name }}</td>
                                    <td width="30%">{{ bid.price }} грн.</td>
                                    <td width="30%">{{ bid.date_created }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--   !product  -->


    <!-- Top Sale -->
    <section id="top-sale">
        <div class="container py-5">
            <h4 class="font-size-20">Інші лоти</h4>
            <hr>
            <!-- carousel -->

            <!-- //carousel -->
        </div>
    </section>
    <!-- !Top Sale -->

</main>

{% endblock content %}

website/templates/website/lot_list.html
{% extends 'website/main.html' %}
{% load static %}
{% load get_query %}

{% block title %}Лоти{% endblock title %}

{% block extra_script %}
<script src="{% static 'scripts/search.js' %}"></script>
{% endblock extra_script %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            {% include 'includes/sidebar.html' %}
        </div>
        <div class="col-md-9 mt-4">
            {% if not lots %}
            <p style="font-size: 30px;">Лотів не знайдено</p>
            {% endif %}
            {% for lot in lots %}
            <div class="card card-body mt-3">
                <div
                    class="media align-items-center align-items-lg-start text-center text-lg-left flex-column flex-lg-row">
                    <div class="mr-2 mb-3 mb-lg-0">
                        {% if lot.first_image.photo.url %}
                        <img src="{{lot.first_image.photo.url}}" width="150" height="150" alt="">
                        {% else %}
                        <img src="{% static 'images/images.png' %}" width="150" height="150" alt="">
                        {% endif %}
                    </div>
                    <div class="media-body">
                        <h6 class="media-title font-weight-semibold"> <a href="{{ lot.get_absolute_url }}"
                                data-abc="true">{{lot.name}}</a></h6>
                        <ul class="list-inline list-inline-dotted mb-3 mb-lg-2">
                            <li class="list-inline-item"><a href="{{ lot.category.get_absolute_url }}" class="text-muted"
                                    data-abc="true">{{ lot.category }}</a></li>
                        </ul>
                        <p class="mb-3">{{lot.description|truncatechars:"200"}}</p>
                        <ul class="list-inline list-inline-dotted mb-0">
                            <li class="list-inline-item">Усі товари <a href="#" data-abc="true">{{ lot.owner }}</a>
                            </li>
                            <li class="list-inline-item"><a href="#" data-abc="true">Додати до бажаного</a></li>
                        </ul>
                    </div>
                    <div class="mt-3 mt-lg-0 ml-lg-3 text-center">
                        <h3 class="mb-0 font-weight-semibold">{{lot.current_price}} грн.</h3>
                        <a href="{{ lot.get_absolute_url }}" class="btn btn-primary mt-5 stretched-link">Детальніше</a>
                    </div>
                </div>
            </div>
            <div class="card-footer w-100 text-muted">
                <div class="row">
                    <div class="col-md-4">
                        <p>Завершується: {{lot.date_end}}</p>
                    </div>
                    <div class="col-md-4">
                        <p class="text-end">Ставки: {{ lot.bidcompanylot_set.count }}</p>
                    </div>
                    <div class="col-md-4 text-right">
                        <p>Стартова ціна: {{lot.price}} грн.</p>
                    </div>
                </div>
            </div>

            <br>


            {% endfor %}
        </div>
    </div>
</div>

{% if is_paginated %}

<hr>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}

        <li class="page-item">
            <a class="page-link" href="{% url 'lots' %}?{% query_transform page=page_obj.previous_page_number %}"
                tabindex="-1">Попередня</a>
        </li>

        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Попередня</a>
        </li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
        <li class="page-item"><a class="page-link"
                href="{% url 'lots' %}?{% query_transform page=forloop.counter %}">{{ forloop.counter }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}

        <li class="page-item">
            <a class="page-link"
                href="{% url 'lots' %}?{% query_transform page=page_obj.next_page_number %}">Наступна</a>
        </li>

        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Наступна</a>
        </li>
        {% endif %}
    </ul>
</nav>



{% endif %}


{% endblock content %}

website/templates/website/profile.html
{% extends 'website/main.html' %}
{% load static %}

{% block content %}
{% if user_profile.profile_pic.url %}
<img src="{{user_profile.profile_pic.url}}" alt="" style="width:150px;">
{% endif %}
<ul>
<li>{{user_profile.name}}</li>
<li>{{user_profile.phone}}</li>
<li>{{user_profile.user.email}}</li>
{% if request.user.company %}
<li>{{user_profile.edrpou}}</li>
<li>{{user_profile.location}}</li>
<li><a href="{{user_profile.website_link}}">{{user_profile.website_link}}</a></li>
{% endif %}
</ul>

<h1>Лоти</h1>

<div class="container">
{% for lot in lots %}

    <div class="card flex-row flex-wrap">
        {% if lot.first_image %}
        <div class="card-header border-0">
            <img src="{{lot.first_image.photo.url}}" alt="" style="width:250px;">
        </div>
        {% endif %}
        <div class="card-block px-2">
            <h4 class="card-title">{{lot.name}}</h4>
            <p class="card-text">{{lot.description|truncatechars:"20"}}</p>
            <a href="{{lot.url}}" class="btn btn-primary stretched-link">Детальніше</a>
        </div>
        <div class="w-100"></div>
        <div class="card-footer w-100 text-muted">
            <div class="row">
                <div class="col-md-6">
                    <p>Завершується: {{lot.date_end}}</p>
                </div>
                <div class="col-md-6">
                    <p class="text-end">Стартова ціна: {{lot.price}} грн.</p>
                </div>
            </div>

        </div>
    </div>
    <br>

{% endfor %}
</div>

<div class="form-container container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% include 'includes/eazy_form.html' with form=client_lot_form %}
    {% include 'includes/eazy_form.html' with form=company_lot_form %}
    {% include 'includes/eazy_form.html' with form=lot_photo_form %}
    
    <button type="submit" class="btn btn-primary">Опублікувати</button>
</form>
</div>

{% endblock content %}